# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lei's Blog
brief-intro: Computer Vision Engineering
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://allylei.github.io" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
twitter_username: lei
facebook_username: lei
github_username:  allyLei
email: ally.sunlei@gmail.com
linkedIn_username: LeiSun
whatsapp_username: 573504676085
instagram_username: lei

description_footer: Learning and practise, always stay foolish and stay young

# comments
# two ways to comment, only choose one, and use your own short name
duoshuo_shortname:
disqus_shortname: lei

# statistic analysis
baidu_tongji_id:
google_analytics_id: UA-113946058-1 # google UserId

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

#sitemap
sitemap:
    filename: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/index.html"
        - "/_post"
        - "/about"
    change_frequency_name: "change_frequency"
    priority_name: "priority"

# paginate
gems: 
    - jekyll-sitemap
    - jekyll-paginate
paginate: 6

